on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        name: "Publish"
        with:
          token: ${{ secrets.NPM_TOKEN }}
          
